"""add study.corresponding_author_name

Revision ID: 2847c985a765
Revises: d2b9a65688ca
Create Date: 2026-07-18 19:41:36.798115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2847c985a765'
down_revision: Union[str, None] = 'd2b9a65688ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('corresponding_author_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'corresponding_author_name')
    # ### end Alembic commands ###
