"""split corresponding_author_contact into email and phone

Revision ID: 52587d8c6b8f
Revises: 2847c985a765
Create Date: 2026-07-18 19:47:21.330758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52587d8c6b8f'
down_revision: Union[str, None] = '2847c985a765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('corresponding_author_email', sa.String(), nullable=True))
    op.add_column('study', sa.Column('corresponding_author_phone', sa.String(), nullable=True))
    op.drop_column('study', 'corresponding_author_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('corresponding_author_contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('study', 'corresponding_author_phone')
    op.drop_column('study', 'corresponding_author_email')
    # ### end Alembic commands ###
