"""restructure contact and surface into templates and actual instances

Revision ID: 683ac9981324
Revises: f1a2b3c4d5e6
Create Date: 2026-07-24 16:24:58.558273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ac9981324'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_set_id'), 'recovery_set', ['id'], unique=True)
    op.create_table('scenario_persistence',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('persistence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persistence_id'], ['persistence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'persistence_id')
    )
    op.create_table('surface_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_of_body_category_id', sa.Integer(), nullable=True),
    sa.Column('body_part_condition_category_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_parts_category_id', sa.Integer(), nullable=True),
    sa.Column('condition_of_item_part_category_id', sa.Integer(), nullable=True),
    sa.Column('surface_material_category_id', sa.Integer(), nullable=True),
    sa.Column('source_of_dna_category_id', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('background_dna', sa.Boolean(), nullable=True),
    sa.Column('prevalence', sa.Boolean(), nullable=True),
    sa.Column('further_description_of_background_and_prevalence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['body_part_condition_category_id'], ['body_part_condition_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condition_of_item_part_category_id'], ['condition_of_item_part_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_parts_category_id'], ['item_parts_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_of_body_category_id'], ['location_of_body_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_of_dna_category_id'], ['source_of_dna_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surface_material_category_id'], ['surface_material_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surface_template_id'), 'surface_template', ['id'], unique=True)
    op.create_table('contact_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_surface_template_id', sa.Integer(), nullable=True),
    sa.Column('recipient_surface_template_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('pressure_estimate_id', sa.Integer(), nullable=True),
    sa.Column('friction_applied', sa.Float(), nullable=True),
    sa.Column('friction_applied_estimate_id', sa.Integer(), nullable=True),
    sa.Column('contact_area', sa.Float(), nullable=True),
    sa.Column('description_of_contact', sa.String(), nullable=True),
    sa.Column('activity_category_id', sa.Integer(), nullable=True),
    sa.Column('condition_during_contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_category_id'], ['activity_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condition_during_contact_id'], ['condition_during_contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_surface_template_id'], ['surface_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['friction_applied_estimate_id'], ['friction_applied_estiamte.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pressure_estimate_id'], ['pressure_estimate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_surface_template_id'], ['surface_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_template_id'), 'contact_template', ['id'], unique=True)
    op.create_table('study_scenario',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'scenario_id')
    )
    op.create_table('scenario_contact_template',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('contact_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_template_id'], ['contact_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'contact_template_id')
    )
    op.add_column('contact', sa.Column('contact_template_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('contact_scenario_id_fkey'), 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'contact_template', ['contact_template_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contact', 'scenario_id')
    op.add_column('recovery', sa.Column('study_id', sa.Integer(), nullable=True))
    op.add_column('recovery', sa.Column('recovery_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recovery', 'recovery_set', ['recovery_set_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recovery', 'study', ['study_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('scenario_persistence_id_fkey'), 'scenario', type_='foreignkey')
    op.drop_constraint(op.f('scenario_study_id_fkey'), 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'study_id')
    op.drop_column('scenario', 'persistence_id')
    op.add_column('surface', sa.Column('surface_template_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('surface_item_id_fkey'), 'surface', type_='foreignkey')
    op.create_foreign_key(None, 'surface', 'surface_template', ['surface_template_id'], ['id'], ondelete='SET NULL')
    op.drop_column('surface', 'prevalence')
    op.drop_column('surface', 'further_description_of_background_and_prevalence')
    op.drop_column('surface', 'background_dna')
    op.drop_column('surface', 'item_id')
    op.drop_column('surface', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surface', sa.Column('photo_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('surface', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('surface', sa.Column('background_dna', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('surface', sa.Column('further_description_of_background_and_prevalence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('surface', sa.Column('prevalence', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'surface', type_='foreignkey')
    op.create_foreign_key(op.f('surface_item_id_fkey'), 'surface', 'item', ['item_id'], ['id'], ondelete='SET NULL')
    op.drop_column('surface', 'surface_template_id')
    op.add_column('scenario', sa.Column('persistence_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scenario', sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('scenario_study_id_fkey'), 'scenario', 'study', ['study_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('scenario_persistence_id_fkey'), 'scenario', 'persistence', ['persistence_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'recovery', type_='foreignkey')
    op.drop_constraint(None, 'recovery', type_='foreignkey')
    op.drop_column('recovery', 'recovery_set_id')
    op.drop_column('recovery', 'study_id')
    op.add_column('contact', sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key(op.f('contact_scenario_id_fkey'), 'contact', 'scenario', ['scenario_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contact', 'contact_template_id')
    op.drop_table('scenario_contact_template')
    op.drop_table('study_scenario')
    op.drop_index(op.f('ix_contact_template_id'), table_name='contact_template')
    op.drop_table('contact_template')
    op.drop_index(op.f('ix_surface_template_id'), table_name='surface_template')
    op.drop_table('surface_template')
    op.drop_table('scenario_persistence')
    op.drop_index(op.f('ix_recovery_set_id'), table_name='recovery_set')
    op.drop_table('recovery_set')
    # ### end Alembic commands ###
