"""custom jwt auth: replace fastapi-users, add laboratory fk to user, add user_token

Revision ID: b67a14a0b4dd
Revises: 
Create Date: 2026-07-17 15:54:31.370799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67a14a0b4dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_category_id'), 'activity_category', ['id'], unique=True)
    op.create_table('body_part_condition_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_part_condition_category_id'), 'body_part_condition_category', ['id'], unique=True)
    op.create_table('condition_of_item_part_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_of_item_part_category_id'), 'condition_of_item_part_category', ['id'], unique=True)
    op.create_table('cutting_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutting_device_id'), 'cutting_device', ['id'], unique=True)
    op.create_table('determination_of_shedding_propensity_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('restrictions_prior_to_sampling', sa.String(), nullable=True),
    sa.Column('monitored_transfer_factors', sa.String(), nullable=True),
    sa.Column('number_of_participants', sa.Integer(), nullable=True),
    sa.Column('replicates', sa.Integer(), nullable=True),
    sa.Column('shedder_test', sa.String(), nullable=True),
    sa.Column('classification_criteria', sa.String(), nullable=True),
    sa.Column('classification_scheme', sa.String(), nullable=True),
    sa.Column('classification_outcome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_determination_of_shedding_propensity_category_id'), 'determination_of_shedding_propensity_category', ['id'], unique=True)
    op.create_table('disturbance_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disturbance_category_id'), 'disturbance_category', ['id'], unique=True)
    op.create_table('experience_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_level_id'), 'experience_level', ['id'], unique=True)
    op.create_table('friction_applied_estiamte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friction_applied_estiamte_id'), 'friction_applied_estiamte', ['id'], unique=True)
    op.create_table('geographic_location_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geographic_location_category_id'), 'geographic_location_category', ['id'], unique=True)
    op.create_table('item_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_category_id'), 'item_category', ['id'], unique=True)
    op.create_table('item_parts_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_parts_category_id'), 'item_parts_category', ['id'], unique=True)
    op.create_table('item_subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_subcategory_id'), 'item_subcategory', ['id'], unique=True)
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('institutional_affiliation', sa.String(), nullable=False),
    sa.Column('director_head_of_laboratory', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laboratory_id'), 'laboratory', ['id'], unique=True)
    op.create_table('location_of_body_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_of_body_category_id'), 'location_of_body_category', ['id'], unique=True)
    op.create_table('picking_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_device_id'), 'picking_device', ['id'], unique=True)
    op.create_table('pressure_estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pressure_estimate_id'), 'pressure_estimate', ['id'], unique=True)
    op.create_table('principle_of_extraction_method_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principle_of_extraction_method_category_id'), 'principle_of_extraction_method_category', ['id'], unique=True)
    op.create_table('principle_of_quant_method_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principle_of_quant_method_category_id'), 'principle_of_quant_method_category', ['id'], unique=True)
    op.create_table('scenario_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_category_id'), 'scenario_category', ['id'], unique=True)
    op.create_table('scraping_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_device_id'), 'scraping_device', ['id'], unique=True)
    op.create_table('skin_disease_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('influence_on_shedding_propensity', sa.Boolean(), nullable=True),
    sa.Column('literature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skin_disease_category_id'), 'skin_disease_category', ['id'], unique=True)
    op.create_table('source_of_dna_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_of_dna_category_id'), 'source_of_dna_category', ['id'], unique=True)
    op.create_table('surface_material_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surface_material_category_id'), 'surface_material_category', ['id'], unique=True)
    op.create_table('swabbing_technique_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swabbing_technique_category_id'), 'swabbing_technique_category', ['id'], unique=True)
    op.create_table('type_of_swab_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_of_swab_category_id'), 'type_of_swab_category', ['id'], unique=True)
    op.create_table('type_of_tape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_of_tape_id'), 'type_of_tape', ['id'], unique=True)
    op.create_table('vacuum_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacuum_device_id'), 'vacuum_device', ['id'], unique=True)
    op.create_table('ce_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('ce_device', sa.String(), nullable=True),
    sa.Column('application_type', sa.String(), nullable=True),
    sa.Column('capillary_length', sa.Integer(), nullable=True),
    sa.Column('polymer', sa.String(), nullable=True),
    sa.Column('dye_set', sa.String(), nullable=True),
    sa.Column('oven_temperature', sa.Float(), nullable=True),
    sa.Column('run_voltage', sa.Float(), nullable=True),
    sa.Column('pre_run_voltage', sa.Float(), nullable=True),
    sa.Column('injection_voltage', sa.Float(), nullable=True),
    sa.Column('run_time', sa.Interval(), nullable=True),
    sa.Column('pre_run_time', sa.Interval(), nullable=True),
    sa.Column('injection_time', sa.Interval(), nullable=True),
    sa.Column('type_of_formamide', sa.String(), nullable=True),
    sa.Column('volume_formamide', sa.Integer(), nullable=True),
    sa.Column('size_standard', sa.String(), nullable=True),
    sa.Column('volume_size_standard', sa.Float(), nullable=True),
    sa.Column('input_volume_pcr_product', sa.Float(), nullable=True),
    sa.Column('final_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ce_method_id'), 'ce_method', ['id'], unique=True)
    op.create_table('condition_during_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('uv_irradiation', sa.Float(), nullable=True),
    sa.Column('indoors', sa.Boolean(), nullable=True),
    sa.Column('change_over_time', sa.Boolean(), nullable=True),
    sa.Column('duration_of_disturbance', sa.Interval(), nullable=True),
    sa.Column('description_of_disturbance', sa.String(), nullable=True),
    sa.Column('disturbance_category_id', sa.Integer(), nullable=True),
    sa.Column('geographic_location_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disturbance_category_id'], ['disturbance_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geographic_location_category_id'], ['geographic_location_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_during_contact_id'), 'condition_during_contact', ['id'], unique=True)
    op.create_table('cutting_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cutting_device_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cutting_device_id'], ['cutting_device.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutting_method_id'), 'cutting_method', ['id'], unique=True)
    op.create_table('epg_analysis_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('genotyping_software', sa.String(), nullable=True),
    sa.Column('analytical_threshold', sa.Integer(), nullable=True),
    sa.Column('application_analytical_threshold', sa.String(), nullable=True),
    sa.Column('stutter_filter', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epg_analysis_method_id'), 'epg_analysis_method', ['id'], unique=True)
    op.create_table('epg_interpretation_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('determination_of_noc', sa.String(), nullable=True),
    sa.Column('statistical_software', sa.String(), nullable=True),
    sa.Column('parameters_modelled_by_software', sa.String(), nullable=True),
    sa.Column('allele_frequency_database', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epg_interpretation_method_id'), 'epg_interpretation_method', ['id'], unique=True)
    op.create_table('extraction_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('principle_of_extraction_method_category_id', sa.Integer(), nullable=True),
    sa.Column('extraction_protocol', sa.String(), nullable=True),
    sa.Column('extraction_platform', sa.String(), nullable=True),
    sa.Column('additional_lysis_buffer_components', sa.String(), nullable=True),
    sa.Column('volume_lysis_buffer_components', sa.Float(), nullable=True),
    sa.Column('lysis_incubation_time', sa.Interval(), nullable=True),
    sa.Column('lysis_incubation_temperature', sa.Float(), nullable=True),
    sa.Column('volume_of_lysate_used_for_extraction', sa.Float(), nullable=True),
    sa.Column('application_of_further_purification_step', sa.Boolean(), nullable=True),
    sa.Column('description_of_further_purification_step', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principle_of_extraction_method_category_id'], ['principle_of_extraction_method_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_method_id'), 'extraction_method', ['id'], unique=True)
    op.create_table('individual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dna_shedding_propensity', sa.String(), nullable=True),
    sa.Column('skin_disease_category_id', sa.Integer(), nullable=True),
    sa.Column('determination_of_shedding_propensity_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['determination_of_shedding_propensity_category_id'], ['determination_of_shedding_propensity_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skin_disease_category_id'], ['skin_disease_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_id'), 'individual', ['id'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_category_id', sa.Integer(), nullable=True),
    sa.Column('item_subcategory_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('picture_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_subcategory_id'], ['item_subcategory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=True)
    op.create_table('pcr_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('pcr_kit', sa.String(), nullable=True),
    sa.Column('thermocycler', sa.String(), nullable=True),
    sa.Column('initial_denaturation_temp', sa.Float(), nullable=True),
    sa.Column('initial_denaturation_time', sa.Interval(), nullable=True),
    sa.Column('no_of_cycles', sa.Integer(), nullable=True),
    sa.Column('denaturation_temp', sa.Float(), nullable=True),
    sa.Column('denaturation_time', sa.Interval(), nullable=True),
    sa.Column('annealing_temp', sa.Float(), nullable=True),
    sa.Column('annealing_time', sa.Interval(), nullable=True),
    sa.Column('elongation_temp', sa.Float(), nullable=True),
    sa.Column('elongation_time', sa.Interval(), nullable=True),
    sa.Column('final_elongation_temp', sa.Float(), nullable=True),
    sa.Column('final_elongation_time', sa.Interval(), nullable=True),
    sa.Column('ramping', sa.Float(), nullable=True),
    sa.Column('total_volume_pcr_reaction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pcr_method_id'), 'pcr_method', ['id'], unique=True)
    op.create_table('persistence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_of_persistence', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('uv_irradiation', sa.Float(), nullable=True),
    sa.Column('indoors', sa.Boolean(), nullable=True),
    sa.Column('change_over_time', sa.Boolean(), nullable=True),
    sa.Column('duration_of_disturbance', sa.Interval(), nullable=True),
    sa.Column('description_of_disturbance', sa.String(), nullable=True),
    sa.Column('disturbance_category_id', sa.Integer(), nullable=True),
    sa.Column('geographic_location_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disturbance_category_id'], ['disturbance_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geographic_location_category_id'], ['geographic_location_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persistence_id'), 'persistence', ['id'], unique=True)
    op.create_table('picking_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('picking_device_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['picking_device_id'], ['picking_device.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_method_id'), 'picking_method', ['id'], unique=True)
    op.create_table('post_pcr_treatment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('application_of_post_pcr_purification_step', sa.Boolean(), nullable=True),
    sa.Column('description_of_post_pcr_purification_step', sa.String(), nullable=True),
    sa.Column('dilution_of_pcr_product', sa.Boolean(), nullable=True),
    sa.Column('dilution_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_pcr_treatment_method_id'), 'post_pcr_treatment_method', ['id'], unique=True)
    op.create_table('quantification_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('principle_of_quant_method_category_id', sa.Integer(), nullable=True),
    sa.Column('kit', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('description_of_protocol', sa.String(), nullable=True),
    sa.Column('abbreviations_to_manufacturers_protocol', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['principle_of_quant_method_category_id'], ['principle_of_quant_method_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantification_method_id'), 'quantification_method', ['id'], unique=True)
    op.create_table('scraping_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraping_device_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scraping_device_id'], ['scraping_device.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_method_id'), 'scraping_method', ['id'], unique=True)
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('plan_a_transfer_experiment', sa.Boolean(), nullable=True),
    sa.Column('add_data_to_repository', sa.Boolean(), nullable=True),
    sa.Column('quality_check_passed', sa.Boolean(), nullable=True),
    sa.Column('corresponding_author_contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=True)
    op.create_table('swab_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wetting_agent', sa.String(), nullable=True),
    sa.Column('volume_of_wetting_agent', sa.Float(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_of_swab_category_id', sa.Integer(), nullable=True),
    sa.Column('swabbing_technique_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['swabbing_technique_category_id'], ['swabbing_technique_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_of_swab_category_id'], ['type_of_swab_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swab_method_id'), 'swab_method', ['id'], unique=True)
    op.create_table('tape_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_tape_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_of_tape_id'], ['type_of_tape.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tape_method_id'), 'tape_method', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vacuum_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacuum_device_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('catalogue_number_of_supplier', sa.String(), nullable=True),
    sa.Column('full_name_as_by_supplier', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vacuum_device_id'], ['vacuum_device.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacuum_method_id'), 'vacuum_method', ['id'], unique=True)
    op.create_table('sampling_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('swab_method_id', sa.Integer(), nullable=True),
    sa.Column('tape_method_id', sa.Integer(), nullable=True),
    sa.Column('vacuum_method_id', sa.Integer(), nullable=True),
    sa.Column('cutting_method_id', sa.Integer(), nullable=True),
    sa.Column('scraping_method_id', sa.Integer(), nullable=True),
    sa.Column('picking_method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cutting_method_id'], ['cutting_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picking_method_id'], ['picking_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraping_method_id'], ['scraping_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['swab_method_id'], ['swab_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tape_method_id'], ['tape_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacuum_method_id'], ['vacuum_method.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sampling_method_id'), 'sampling_method', ['id'], unique=True)
    op.create_table('surface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('location_of_body_category_id', sa.Integer(), nullable=True),
    sa.Column('body_part_condition_category_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_parts_category_id', sa.Integer(), nullable=True),
    sa.Column('condition_of_item_part_category_id', sa.Integer(), nullable=True),
    sa.Column('surface_material_category_id', sa.Integer(), nullable=True),
    sa.Column('source_of_dna_category_id', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('background_dna', sa.Boolean(), nullable=True),
    sa.Column('prevalence', sa.Boolean(), nullable=True),
    sa.Column('further_description_of_background_and_prevalence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['body_part_condition_category_id'], ['body_part_condition_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condition_of_item_part_category_id'], ['condition_of_item_part_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['individual_id'], ['individual.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_parts_category_id'], ['item_parts_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_of_body_category_id'], ['location_of_body_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_of_dna_category_id'], ['source_of_dna_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surface_material_category_id'], ['surface_material_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surface_id'), 'surface', ['id'], unique=True)
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_token_hash'), 'user_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_token_user_id'), 'user_token', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_surface_id', sa.Integer(), nullable=True),
    sa.Column('recipient_surface_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('pressure_estimate_id', sa.Integer(), nullable=True),
    sa.Column('friction_applied', sa.Float(), nullable=True),
    sa.Column('friction_applied_estimate_id', sa.Integer(), nullable=True),
    sa.Column('contact_area', sa.Float(), nullable=True),
    sa.Column('description_of_contact', sa.String(), nullable=True),
    sa.Column('activity_category_id', sa.Integer(), nullable=True),
    sa.Column('condition_during_contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_category_id'], ['activity_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['condition_during_contact_id'], ['condition_during_contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_surface_id'], ['surface.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['friction_applied_estimate_id'], ['friction_applied_estiamte.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pressure_estimate_id'], ['pressure_estimate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_surface_id'], ['surface.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=True)
    op.create_table('recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surface_id', sa.Integer(), nullable=True),
    sa.Column('sampling_method_id', sa.Integer(), nullable=True),
    sa.Column('extraction_method_id', sa.Integer(), nullable=True),
    sa.Column('elution_volume', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('experience_level_of_sampler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experience_level_of_sampler_id'], ['experience_level.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_method_id'], ['extraction_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sampling_method_id'], ['sampling_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['surface_id'], ['surface.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_id'), 'recovery', ['id'], unique=True)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantification_method_id', sa.Integer(), nullable=True),
    sa.Column('recovery_id', sa.Integer(), nullable=True),
    sa.Column('dna_concentration', sa.Float(), nullable=True),
    sa.Column('degradation', sa.String(), nullable=True),
    sa.Column('inhibition', sa.Boolean(), nullable=True),
    sa.Column('dna_quantity', sa.Float(), nullable=True),
    sa.Column('pcr_method_id', sa.Integer(), nullable=True),
    sa.Column('sample_input_volume_in_pcr', sa.Float(), nullable=True),
    sa.Column('dna_input_amount_in_pcr', sa.Float(), nullable=True),
    sa.Column('post_pcr_treatment_method_id', sa.Integer(), nullable=True),
    sa.Column('ce_method_id', sa.Integer(), nullable=True),
    sa.Column('epg_analysis_method_id', sa.Integer(), nullable=True),
    sa.Column('epg_interpretation_method_id', sa.Integer(), nullable=True),
    sa.Column('no_of_contributors', sa.Integer(), nullable=True),
    sa.Column('mixture_proportion', sa.Float(), nullable=True),
    sa.Column('total_rfu', sa.Integer(), nullable=True),
    sa.Column('total_no_of_alleles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ce_method_id'], ['ce_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['epg_analysis_method_id'], ['epg_analysis_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['epg_interpretation_method_id'], ['epg_interpretation_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pcr_method_id'], ['pcr_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_pcr_treatment_method_id'], ['post_pcr_treatment_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quantification_method_id'], ['quantification_method.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_id'], ['recovery.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realistic', sa.Boolean(), nullable=False),
    sa.Column('scenario_category_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('persistence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persistence_id'], ['persistence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_category_id'], ['scenario_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['study.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_id'), 'scenario', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_id'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_recovery_id'), table_name='recovery')
    op.drop_table('recovery')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_user_token_user_id'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_token_hash'), table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_surface_id'), table_name='surface')
    op.drop_table('surface')
    op.drop_index(op.f('ix_sampling_method_id'), table_name='sampling_method')
    op.drop_table('sampling_method')
    op.drop_index(op.f('ix_vacuum_method_id'), table_name='vacuum_method')
    op.drop_table('vacuum_method')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tape_method_id'), table_name='tape_method')
    op.drop_table('tape_method')
    op.drop_index(op.f('ix_swab_method_id'), table_name='swab_method')
    op.drop_table('swab_method')
    op.drop_index(op.f('ix_study_id'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_scraping_method_id'), table_name='scraping_method')
    op.drop_table('scraping_method')
    op.drop_index(op.f('ix_quantification_method_id'), table_name='quantification_method')
    op.drop_table('quantification_method')
    op.drop_index(op.f('ix_post_pcr_treatment_method_id'), table_name='post_pcr_treatment_method')
    op.drop_table('post_pcr_treatment_method')
    op.drop_index(op.f('ix_picking_method_id'), table_name='picking_method')
    op.drop_table('picking_method')
    op.drop_index(op.f('ix_persistence_id'), table_name='persistence')
    op.drop_table('persistence')
    op.drop_index(op.f('ix_pcr_method_id'), table_name='pcr_method')
    op.drop_table('pcr_method')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_individual_id'), table_name='individual')
    op.drop_table('individual')
    op.drop_index(op.f('ix_extraction_method_id'), table_name='extraction_method')
    op.drop_table('extraction_method')
    op.drop_index(op.f('ix_epg_interpretation_method_id'), table_name='epg_interpretation_method')
    op.drop_table('epg_interpretation_method')
    op.drop_index(op.f('ix_epg_analysis_method_id'), table_name='epg_analysis_method')
    op.drop_table('epg_analysis_method')
    op.drop_index(op.f('ix_cutting_method_id'), table_name='cutting_method')
    op.drop_table('cutting_method')
    op.drop_index(op.f('ix_condition_during_contact_id'), table_name='condition_during_contact')
    op.drop_table('condition_during_contact')
    op.drop_index(op.f('ix_ce_method_id'), table_name='ce_method')
    op.drop_table('ce_method')
    op.drop_index(op.f('ix_vacuum_device_id'), table_name='vacuum_device')
    op.drop_table('vacuum_device')
    op.drop_index(op.f('ix_type_of_tape_id'), table_name='type_of_tape')
    op.drop_table('type_of_tape')
    op.drop_index(op.f('ix_type_of_swab_category_id'), table_name='type_of_swab_category')
    op.drop_table('type_of_swab_category')
    op.drop_index(op.f('ix_swabbing_technique_category_id'), table_name='swabbing_technique_category')
    op.drop_table('swabbing_technique_category')
    op.drop_index(op.f('ix_surface_material_category_id'), table_name='surface_material_category')
    op.drop_table('surface_material_category')
    op.drop_index(op.f('ix_source_of_dna_category_id'), table_name='source_of_dna_category')
    op.drop_table('source_of_dna_category')
    op.drop_index(op.f('ix_skin_disease_category_id'), table_name='skin_disease_category')
    op.drop_table('skin_disease_category')
    op.drop_index(op.f('ix_scraping_device_id'), table_name='scraping_device')
    op.drop_table('scraping_device')
    op.drop_index(op.f('ix_scenario_category_id'), table_name='scenario_category')
    op.drop_table('scenario_category')
    op.drop_index(op.f('ix_principle_of_quant_method_category_id'), table_name='principle_of_quant_method_category')
    op.drop_table('principle_of_quant_method_category')
    op.drop_index(op.f('ix_principle_of_extraction_method_category_id'), table_name='principle_of_extraction_method_category')
    op.drop_table('principle_of_extraction_method_category')
    op.drop_index(op.f('ix_pressure_estimate_id'), table_name='pressure_estimate')
    op.drop_table('pressure_estimate')
    op.drop_index(op.f('ix_picking_device_id'), table_name='picking_device')
    op.drop_table('picking_device')
    op.drop_index(op.f('ix_location_of_body_category_id'), table_name='location_of_body_category')
    op.drop_table('location_of_body_category')
    op.drop_index(op.f('ix_laboratory_id'), table_name='laboratory')
    op.drop_table('laboratory')
    op.drop_index(op.f('ix_item_subcategory_id'), table_name='item_subcategory')
    op.drop_table('item_subcategory')
    op.drop_index(op.f('ix_item_parts_category_id'), table_name='item_parts_category')
    op.drop_table('item_parts_category')
    op.drop_index(op.f('ix_item_category_id'), table_name='item_category')
    op.drop_table('item_category')
    op.drop_index(op.f('ix_geographic_location_category_id'), table_name='geographic_location_category')
    op.drop_table('geographic_location_category')
    op.drop_index(op.f('ix_friction_applied_estiamte_id'), table_name='friction_applied_estiamte')
    op.drop_table('friction_applied_estiamte')
    op.drop_index(op.f('ix_experience_level_id'), table_name='experience_level')
    op.drop_table('experience_level')
    op.drop_index(op.f('ix_disturbance_category_id'), table_name='disturbance_category')
    op.drop_table('disturbance_category')
    op.drop_index(op.f('ix_determination_of_shedding_propensity_category_id'), table_name='determination_of_shedding_propensity_category')
    op.drop_table('determination_of_shedding_propensity_category')
    op.drop_index(op.f('ix_cutting_device_id'), table_name='cutting_device')
    op.drop_table('cutting_device')
    op.drop_index(op.f('ix_condition_of_item_part_category_id'), table_name='condition_of_item_part_category')
    op.drop_table('condition_of_item_part_category')
    op.drop_index(op.f('ix_body_part_condition_category_id'), table_name='body_part_condition_category')
    op.drop_table('body_part_condition_category')
    op.drop_index(op.f('ix_activity_category_id'), table_name='activity_category')
    op.drop_table('activity_category')
    # ### end Alembic commands ###
