"""make laboratory address fields optional

Revision ID: c09977495acd
Revises: b67a14a0b4dd
Create Date: 2026-07-17 15:56:27.644711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09977495acd'
down_revision: Union[str, None] = 'b67a14a0b4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'institutional_affiliation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'director_head_of_laboratory',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('laboratory', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laboratory', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'director_head_of_laboratory',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'institutional_affiliation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('laboratory', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
