"""add user passkey_prompt_dismissed

Revision ID: cc4448bf52aa
Revises: e28a22be3bfd
Create Date: 2026-07-21 15:03:07.962422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4448bf52aa'
down_revision: Union[str, None] = 'e28a22be3bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passkey_prompt_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passkey_prompt_dismissed')
    # ### end Alembic commands ###
