"""add webauthn credentials

Revision ID: e28a22be3bfd
Revises: a1b2c3d4e5f6
Create Date: 2026-07-21 14:56:37.721536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28a22be3bfd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_challenge_user_id'), 'webauthn_challenge', ['user_id'], unique=False)
    op.create_table('webauthn_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credential_credential_id'), 'webauthn_credential', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credential_user_id'), 'webauthn_credential', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credential_user_id'), table_name='webauthn_credential')
    op.drop_index(op.f('ix_webauthn_credential_credential_id'), table_name='webauthn_credential')
    op.drop_table('webauthn_credential')
    op.drop_index(op.f('ix_webauthn_challenge_user_id'), table_name='webauthn_challenge')
    op.drop_table('webauthn_challenge')
    # ### end Alembic commands ###
